plugins {
    id 'java-library'
    id 'com.google.protobuf' version '0.9.4'
}

group = 'com.dealership'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    api 'io.grpc:grpc-protobuf:1.63.0'
    api 'io.grpc:grpc-stub:1.63.0'
    api 'com.google.protobuf:protobuf-java:3.25.5'

    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'
}

protobuf {
    protoc {
        artifact = 'com.google.protobuf:protoc:3.25.5'
    }

    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.66.0'
        }
    }

    generateProtoTasks {
        all().configureEach { task ->
            task.plugins {
                grpc {}
            }
        }
    }
}